services:
  postgresdb:
    image: postgres:18.0-trixie
    container_name: cms_postgresdb
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_data_cms:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d
    # - /tmp/foo/root/.borgmatic/postgresql_databases/api-db-service/cms:/data/cms
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=cms
      - POSTGRES_PASSWORD=cmspass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "dbname=cms user=cms"]
      interval: 10s
      timeout: 5s
      retries: 3
  backend:
    build:
      context: ../backend
    container_name: cms_backend
    ports:
      - 127.0.0.1:8000:80
    environment:
      WEB_CONCURRENCY: 1
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cms
    depends_on:
      postgresdb:
        condition: service_healthy
  backend-tests:
    build:
      dockerfile: ../dev/backend-tests/Dockerfile
      context: ../backend
    container_name: cms_backend-tests
    command: tail -f /dev/null
    volumes:
      - ../backend/src:/app/src
      - ../backend/tests:/app/tests
    environment:
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cmstest
    depends_on:
      - postgresdb
  frontend:
    build: ../frontend
    container_name: cms_frontend
    volumes:
      - ./frontend-dev/config.json:/usr/share/nginx/html/config.json:ro
    ports:
      - 127.0.0.1:8001:80
    depends_on:
      backend:
        condition: service_healthy
  frontend-dev:
    build:
      dockerfile: ../dev/frontend-dev/Dockerfile
      context: ../frontend
    container_name: zf_frontend-dev
    volumes:
      - ../frontend/src:/app/src
      - ./frontend-dev/config.json:/app/public/config.json:ro
    ports:
      - 127.0.0.1:8002:80
    depends_on:
      backend:
        condition: service_healthy
volumes:
  pg_data_cms:
