services:
  postgresdb:
    image: postgres:18.0-trixie
    container_name: cms_postgresdb
    ports:
      - 127.0.0.1:37602:5432
    volumes:
      - pg_data_cms:/var/lib/postgresql
      - ./postgres-initdb:/docker-entrypoint-initdb.d
    # - /tmp/foo/root/.borgmatic/postgresql_databases/api-db-service/cms:/data/cms
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=cms
      - POSTGRES_PASSWORD=cmspass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "dbname=cms user=cms"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile-api
    container_name: cms_api
    volumes:
      - ../backend/maint-scripts:/app/maint-scripts
      - ../backend/src/cms_backend:/usr/local/lib/python3.13/site-packages/cms_backend
    ports:
      - 127.0.0.1:37601:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      DEBUG: 1
      WEB_CONCURRENCY: 1
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cms
      ALLOWED_ORIGINS: http://localhost:37600,http://localhost:37603
      OAUTH_JWKS_URI: https://login-staging.kiwix.org/.well-known/jwks.json
      OAUTH_ISSUER: https://login-staging.kiwix.org
      OAUTH_SESSION_AUDIENCE_ID: 309693e7-ad5e-4379-bf93-ba89314230fd
      OAUTH_SESSION_LOGIN_REQUIRE_2FA: true
      CREATE_NEW_OAUTH_ACCOUNT: true
      AUTH_MODES: local
      ALEMBIC_UPGRADE_HEAD_ON_START: true
      JWT_SECRET: DH8kSxcflUVfNRdkEiJJCn2dOOKI3qfw
      INIT_USERNAME: admin
      INIT_PASSWORD: admin_pass
    command:
      - uvicorn
      - cms_backend.api.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --proxy-headers
      - --forwarded-allow-ips
      - "*"
      - --reload
      - --reload-dir
      - /usr/local/lib/python3.13/site-packages/cms_backend
    depends_on:
      postgresdb:
        condition: service_healthy
  mill:
    build:
      context: ../backend
      dockerfile: Dockerfile-mill
    container_name: cms_mill
    volumes:
      - ../backend/maint-scripts:/app/maint-scripts
      - ../backend/src/cms_backend:/usr/local/lib/python3.13/site-packages/cms_backend
      - ./scripts:/scripts
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cms
      QUARANTINE_WAREHOUSE_ID: 11111111-1111-1111-1111-111111111111
      QUARANTINE_BASE_PATH: quarantine
      STAGING_WAREHOUSE_ID: 11111111-1111-1111-1111-111111111111
      STAGING_BASE_PATH: staging
    depends_on:
      postgresdb:
        condition: service_healthy
  shuttle:
    build:
      context: ../backend
      dockerfile: Dockerfile-shuttle
    container_name: cms_shuttle
    volumes:
      - ../backend/maint-scripts:/app/maint-scripts
      - ../backend/src/cms_backend:/usr/local/lib/python3.13/site-packages/cms_backend
      - ./scripts:/scripts
      - ./warehouses:/warehouses
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cms
      LOCAL_WAREHOUSE_PATHS: "11111111-1111-1111-1111-111111111111:/warehouses/hidden,22222222-2222-2222-2222-222222222222:/warehouses/prod,33333333-3333-3333-3333-333333333333:/warehouses/client1"
    depends_on:
      postgresdb:
        condition: service_healthy
  backend-tests:
    build:
      dockerfile: ../dev/backend-tests/Dockerfile
      context: ../backend
    container_name: cms_backend-tests
    command: tail -f /dev/null
    volumes:
      - ../backend/src:/app/src
      - ../backend/tests:/app/tests
    environment:
      DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cmstest
      ALEMBIC_UPGRADE_HEAD_ON_START: false
      AUTH_MODES: local
      JWT_SECRET: DH8kSxcflUVfNRdkEiJJCn2dOOKI3qfw
    depends_on:
      - postgresdb
  frontend:
    build: ../frontend
    container_name: cms_frontend
    volumes:
      - ./frontend-dev/config.json:/usr/share/nginx/html/config.json:ro
    ports:
      - 127.0.0.1:37603:80
    depends_on:
      api:
        condition: service_healthy
  frontend-dev:
    build:
      dockerfile: ../dev/frontend-dev/Dockerfile
      context: ../frontend
    container_name: cms_frontend-dev
    volumes:
      - ../frontend/src:/app/src
      - ./frontend-dev/config.json:/app/public/config.json:ro
    ports:
      - 127.0.0.1:37600:80
    depends_on:
      api:
        condition: service_healthy

  healthcheck:
    build: ../healthcheck
    container_name: cms_healthcheck
    ports:
      - 127.0.0.1:37604:80
    depends_on:
      api:
        condition: service_healthy
    environment:
      CMS_DATABASE_URL: postgresql+psycopg://cms:cmspass@postgresdb:5432/cms
      CMS_FRONTEND_URL: http://frontend
      CMS_USERNAME: cms
      CMS_PASSWORD: cms_pass
      CMS_API_URL: http://api/v1
    volumes:
      - ../healthcheck/src/healthcheck:/usr/local/lib/python3.13/site-packages/healthcheck
    command:
      - uvicorn
      - healthcheck.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --proxy-headers
      - --forwarded-allow-ips
      - "*"
      - --reload
      - --reload-dir
      - /usr/local/lib/python3.13/site-packages/healthcheck
    profiles:
      - healthcheck

volumes:
  pg_data_cms:
